name: $(Build.BuildId)

trigger:
 branches:
   include:
     - master/Chapter-10-(LookupValue-Extension)

variables:
- group: 'PipelineVariables'

pool: default

jobs:
- job: default
  timeoutInMinutes: 600
  pool: default

  steps:
  - checkout: self
    clean: true 

  - task: ALOpsDockerCreate@1
    displayName: 'ALOPS - Create Docker Image' # It will reuse the image if already exists, or build one if it doesn't.
    inputs:
      artifactversion: '$(artifactVersion)'
      artifactcountry: '$(artifactCountry)'
      forcecreateimage: $(forceCreateImage)
      includetesttoolkit: true
      includetestlibrariesonly: true

  - task: ALOpsDockerStart@1
    displayName: 'ALOPS - Start Docker Container' # No need to provide any details - it will get the details from previous step

  - task: ALOpsDockerWait@1
    displayName: 'ALOPS - Wait for Docker Container to start'
    inputs:
      search_string: 'Ready for connections!'

  - task: ALOpsLicenseImport@1
    displayName: 'ALOPS - License Import'
    inputs:
      usedocker: true
      license_path: '$(LuxBeheerBcDevLicense)'

  - task: ALOpsAppPublish@1
    displayName: 'ALOPS - Install specific test app(s)'
    inputs:
      usedocker: true
      installaltesttool: true
      skip_verification: true
      install_al_app_names: |
        Tests-VAT

  - task: ALOpsAppTest@1
    condition: ne(variables.useDisabledTestsJson, true)
    displayName: 'ALOPS - Run Tests-VAT'
    inputs:
      usedocker: true
      disabledtests: '$(Build.SourcesDirectory)/Chapter 10 (LookupValue Extension)/test/DisabledTests.json'
      import_testtoolkit: false
      import_action: 'Skip'
      testpage: '130455'
      extensionid: '0f0955b8-92e2-4ce2-a580-3c4583dde9ae' # Tests-VAT
      failed_test_action: 'Ignore'
    continueOnError: true
    timeoutInMinutes: 360

  - task: ALOpsAppTest@1
    condition: eq(variables.useDisabledTestsJson, true)
    displayName: 'ALOPS - Run Tests-VAT'
    inputs:
      usedocker: true
      disabledtests: '$(Build.SourcesDirectory)/Chapter 10 (LookupValue Extension)/test/DisabledTests.json'
      import_testtoolkit: false
      import_action: 'Skip'
      testpage: '130455'
      extensionid: '0f0955b8-92e2-4ce2-a580-3c4583dde9ae' # Tests-VAT
      failed_test_action: 'Ignore'
    continueOnError: true
    timeoutInMinutes: 360

  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/TestResults.xml'
    inputs:
      testResultsFormat: XUnit
      testResultsFiles: '**/TestResults.xml'
      failTaskOnFailedTests: true
      testRunTitle: 'BC Test Results: $(Build.BuildId)'

  - task: ALOpsDockerRemove@1
    displayName: 'ALOPS - Remove Docker Container'
    enabled: true
    condition: always()