name: $(Build.BuildId)

trigger:
 branches:
   include:
     - master/Chapter-10-(LookupValue-Extension)

variables:
- group: 'PipelineVariables'

pool: default

jobs:
- job: default
  timeoutInMinutes: 600
  pool: default

  steps:
  - checkout: self
    clean: true 

  - task: ALOpsDockerCreate@1
    displayName: 'ALOPS - Create Docker Image' # It will reuse the image if already exists, or build one if it doesn't.
    inputs:
      artifactversion: '$(artifactVersion)'
      artifactcountry: '$(artifactCountry)'
      forcecreateimage: $(forceCreateImage)
      includetesttoolkit: true
      includetestlibrariesonly: true

  - task: ALOpsDockerStart@1
    displayName: 'ALOPS - Start Docker Container' # No need to provide any details - it will get the details from previous step
    inputs:
      enable_api_services: true

  - task: ALOpsDockerWait@1
    displayName: 'ALOPS - Wait for Docker Container to start'
    inputs:
      search_string: 'Ready for connections!'

  - task: ALOpsAppPublish@1
    displayName: 'ALOPS - Install specific test app(s)'
    inputs:
      usedocker: true
      installaltesttool: true
      skip_verification: true
      install_al_app_names: |
        Tests-Fixed Asset

  - task: ALOpsAppCompiler@1
    displayName: 'ALOPS - Compile Extension: App'
    inputs:
      usedocker: true
      nav_app_version: '?.?.[yyyyWW].*'
      targetproject: 'Chapter 10 (LookupValue Extension)/app.json'
      app_file_suffix: '_APP'                                 # A trick to uniquely identify the APP (from the TEST-app)

  - task: ALOpsAppPublish@1
    displayName: 'ALOPS - Publish Extension'
    inputs:
      usedocker: true
      nav_artifact_app_filter: '*.app'
      skip_verification: true

  - task: ALOpsAppTest@1
    condition: eq(variables.useDisabledTestsJson, false)
    displayName: 'ALOPS - Run Tests-Fixed Asset'
    inputs:
      usedocker: true
      import_testtoolkit: false
      import_action: 'Skip'
      testpage: '130455'
      extensionid: 'c81764a5-be79-4d50-ba3e-4ade02073780' # Tests-Fixed Asset
      failed_test_action: 'Ignore'
    continueOnError: true
    timeoutInMinutes: 360

  - task: ALOpsAppTest@1
    condition: eq(variables.useDisabledTestsJson, true)
    displayName: 'ALOPS - Run Tests-Fixed Asset'
    inputs:
      usedocker: true
      disabledtests: '$(Build.SourcesDirectory)/Chapter 10 (LookupValue Extension)/disabledtests/DisabledTests.json'
      import_testtoolkit: false
      import_action: 'Skip'
      testpage: '130455'
      extensionid: 'c81764a5-be79-4d50-ba3e-4ade02073780' # Tests-Fixed Asset
      failed_test_action: 'Ignore'
    continueOnError: true
    timeoutInMinutes: 360

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFormat: XUnit
      testResultsFiles: '**/TestResults.xml'
      failTaskOnFailedTests: true
      testRunTitle: 'BC Test Results: $(Build.BuildId)'

  - task: PowerShell@2
    displayName: "Create DisabledTests.json"
    inputs:
      filePath: '$(Build.SourcesDirectory)/Chapter 10 (LookupValue Extension)/disabledtests/ConvertTo-DisabledTests.ps1'
      arguments: '-inputFolderPath ''$(System.DefaultWorkingDirectory)/'''
      errorActionPreference: 'continue'
    condition: always()

  - task: CopyFiles@2
    displayName: 'Copy Test Artifacts to $(Agent.BuildDirectory)/TestResults'
    inputs:
      SourceFolder: '$(Build.Sourcesdirectory)'
      Contents: ?(TestResults.xml|DisabledTests.json)
      TargetFolder: '$(Agent.BuildDirectory)/TestResults'
    condition: always()

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Test Artifacts: TestResults.xml and DisabledTests.json'
    inputs:
      targetPath: '$(Agent.BuildDirectory)/TestResults'
      artifact: 'TestResults'
      publishLocation: 'pipeline'
    condition: always()

  - task: ALOpsDockerRemove@1
    displayName: 'ALOPS - Remove Docker Container'
    enabled: true
    inputs:
      createsqlbackup: $(createSqlBackup)
    condition: always()